apiVersion : apps/v1
kind: Deployment
metadata:
  name: yihanfirstaksappdeployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yihanfirstaksappdeployment
  template:
    metadata:
      labels:
        app: yihanfirstaksappdeployment 
    spec:
      containers:
        - name: yihanfirstaksappdeployment 
          image: yihansecondcontainerregistry.azurecr.io/yihanfirstaksappdeployment
          ports:
          - containerPort: 8080